ovs/urls.py
from django.contrib import admin
from django.urls import path
from poll import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homeView, name='home'),
    path('register/', views.registrationView, name='registration'),
    path('login/', views.loginView, name='login'),
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('logout/', views.logoutView, name='logout'),
    path('position/', views.positionView, name='position'),
    path('candidate/<int:pos>/', views.candidateView, name='candidate'),
    path('candidate/detail/<int:id>/', views.candidateDetailView, name='detail'),
    path('result/', views.resultView, name='result'),
    path('changepass/', views.changePasswordView, name='changepass'),
    path('editprofile/', views.editProfileView, name='editprofile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Online Voting System"
admin.site.index_title = "Welcome to online voting system admin panel"
admin.site.site_title = "OVS"

poll/models.py
from django.db import models
from django.contrib.auth.models import User

class Position(models.Model):
    title = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.title


class Candidate(models.Model):
    name = models.CharField(max_length=50)
    total_vote = models.IntegerField(default=0, editable=False)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name="Candidate Pic", upload_to='images/')
    def __str__(self):
        return "{} - {}".format(self.name, self.position.title)


class ControlVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.user, self.position, self.status)

poll/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput,
        }



class ChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

poll/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponseRedirect
from .forms import RegistrationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .models import Candidate,ControlVote,Position
from .forms import ChangeForm

def homeView(request):
    return render(request, "poll/home.html")

def registrationView(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['password'] == cd['confirm_password']:
                obj = form.save(commit=False)
                obj.set_password(obj.password)
                obj.save()
                messages.success(request, 'You have been registered.')
                return redirect('home')
            else:
                return render(request, "poll/registration.html", {'form':form,'note':'password must match'})
    else:
        form = RegistrationForm()

    return render(request, "poll/registration.html", {'form':form})

def loginView(request):
    if request.method == "POST":
        usern = request.POST.get('username')
        passw = request.POST.get('password')
        user = authenticate(request, username=usern, password=passw)
        if user is not None:
            login(request,user)
            return redirect('dashboard')
        else:
            messages.success(request, 'Invalid username or password!')
            return render(request, "poll/login.html")
    else:
        return render(request, "poll/login.html")


@login_required
def logoutView(request):
    logout(request)
    return redirect('home')

@login_required
def dashboardView(request):
    return render(request, "poll/dashboard.html")

@login_required
def positionView(request):
    obj = Position.objects.all()
    return render(request, "poll/position.html", {'obj':obj})

@login_required
def candidateView(request, pos):
    obj = get_object_or_404(Position, pk = pos)
    if request.method == "POST":

        temp = ControlVote.objects.get_or_create(user=request.user, position=obj)[0]

        if temp.status == False:
            temp2 = Candidate.objects.get(pk=request.POST.get(obj.title))
            temp2.total_vote += 1
            temp2.save()
            temp.status = True
            temp.save()
            return HttpResponseRedirect('/position/')
        else:
            messages.success(request, 'you have already been voted this position.')
            return render(request, 'poll/candidate.html', {'obj':obj})
    else:
        return render(request, 'poll/candidate.html', {'obj':obj})

@login_required
def resultView(request):
    obj = Candidate.objects.all().order_by('position','-total_vote')
    return render(request, "poll/result.html", {'obj':obj})

@login_required
def candidateDetailView(request, id):
    obj = get_object_or_404(Candidate, pk=id)
    return render(request, "poll/candidate_detail.html", {'obj':obj})


@login_required
def changePasswordView(request):
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('dashboard')
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, "poll/password.html", {'form':form})


@login_required
def editProfileView(request):
    if request.method == "POST":
        form = ChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = ChangeForm(instance=request.user)
    return render(request, "poll/edit_profile.html", {'form':form})

poll/templates/poll/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color:powderblue;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Online Voting System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          <a class="nav-item nav-link" href="{% url 'editprofile' %}">Edit Profile</a>
          <a class="nav-item nav-link" href="{% url 'changepass' %}">Change Password</a>
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'registration' %}">Register</a>
        {% endif %}

      </div>
    </div>
  </nav>
  <br>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

poll/templates/poll/candidate.html
{% extends "poll/base.html" %}

{% block title %}Candidate{% endblock %}

{% block content %}

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <h2>Available Candidates of {{ obj.title }}</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% for c in obj.candidate_set.all %}
      <!-- <input type="radio" name="{{ c.position}}" value="{{c.id}}" required> <strong>{{c.name}} <a href="{% url 'detail' c.id %}">Detail</a></strong>
     <br> -->
     <div class="custom-control custom-radio">
      <input type="radio" id="id_{{c.id}}" name="{{ c.position}}" value="{{c.id}}" class="custom-control-input" required>
      <label class="custom-control-label" for="id_{{c.id}}">{{c.name}} <a href="{% url 'detail' c.id %}">Detail</a></label>
    </div>
    {% empty %}
      <p>No Candidates Available</p>
    {% endfor %}
    <br><input type="submit" class="btn btn-outline-success btn-sm" value="VOTE">
  </form>
  <br><p><a href="{% url 'position' %}">Back to Poll</a></p>
{% endblock %}

poll/templates/poll/candidate_detail.html
{% extends "poll/base.html" %}

{% block title %}Candidate Details{% endblock %}

{% block content %}
<div class="jumbotron">
  <center>
  <table class="table">
    <tr>
      <td><img src="{{ obj.image.url }}" width="220" height="280" class="img-fluid"></td>
    </tr>
    <tr>
      <td>
        <h3>Name: {{ obj.name }}</h3>
        <h5>Position: {{ obj.position }}</h5>
      </td>
    </tr>
  </table>
</center>
</div>

{% endblock %}

poll/templates/poll/dashboard.html
{% extends "poll/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <h2>Hi, {{request.user.get_full_name }}</h2>
  <h3><a href="{% url 'position' %}">Click Here To Vote</a></h3>
  <h3><a href="{% url 'result' %}">Click Here To See Result</a></h3>
{% endblock %}

poll/templates/poll/edit_profile.html
{% extends "poll/base.html" %}

{% block title %}Update Profile{% endblock %}

{% block content %}
  {% load widget_tweaks %}
  <div class="jumbotron">
    <h2>Update Profile</h2>

    <form action="" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
            {% for error in field.errors %}
              <ul>
                <li>{{error}}</li>
              </ul>
            {% endfor %}
          {% endif %}
          {{ field.label_tag }}
          {% render_field field class="form-control" %}
          {% if field.help_text %}
            <small class="form-text text-muted">{{field.help_text}}</small>
          {% endif %}
        </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary btn-sm" value="Update">
    </form>
  </div>

{% endblock %}

poll/templates/poll/home.html
{% extends "poll/base.html" %}

{% block title %}Online Voting System{% endblock %}

{% block content %}
<div class="jumbotron">
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
  <h1>Welcome to Online Voting System</h1>
  <h3>This is a simple voting application for small organization.</h3>
</div>

{% endblock %}

poll/templates/poll/login.html
{% extends "poll/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="jumbotron">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <h2>User Login</h2>
      <form action="." method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_username">Username:</label>
          <input type="text" name="username" class="form-control" id="id_username" required>
        </div>
        <div class="form-group">
          <label for="id_password">Password:</label>
          <input type="password" name="password" class="form-control" id="id_password" required>
        </div>

        <input type="submit" class="btn btn-primary btn-sm" value="Login">
      </form>
    </div>

{% endblock %}

poll/templates/poll/password.html
{% extends "poll/base.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="jumbotron">
  <h3>Password Change Form</h3>
  <form action="." method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">

        {% if field.errors %}
          {% for error in field.errors %}
            <ul>
              <li>{{error}}</li>
            </ul>
          {% endfor %}
        {% endif %}

        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{field.help_text}}</small>
        {% endif %}
      </div>
    {% endfor %}
    <input type="submit" class="btn btn-sm btn-primary" value="Update">
  </form>
</div>

{% endblock %}

poll/templates/poll/position.html
{% extends "poll/base.html" %}

{% block title %}{% endblock %}

{% block content %}
  <h2>Available Position For Vote</h2>
  <ul>
    {% for i in obj %}
      <li><a href="{% url 'candidate' i.id %}">{{i.title}}</a></li>
    {% empty %}
      <p>No Positions Available</p>
    {% endfor %}
  </ul>
{% endblock %}

poll/templates/poll/registration.html
{% extends "poll/base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
  {% load widget_tweaks %}
  <div class="jumbotron">
    <h2>User Registration</h2>
    {% if note %}
      <h3 class="text text-muted">{{note}}</h3>
    {% endif %}
    <form action="" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
            {% for error in field.errors %}
              <ul>
                <li>{{error}}</li>
              </ul>
            {% endfor %}
          {% endif %}
          {{ field.label_tag }}
          {% render_field field class="form-control" %}
          {% if field.help_text %}
            <small class="form-text text-muted">{{field.help_text}}</small>
          {% endif %}
        </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary btn-sm" value="Sign Up">
    </form>
  </div>

{% endblock %}

poll/templates/poll/result.html
{% extends "poll/base.html" %}

{% block title %}Result Page{% endblock %}

{% block content %}
  <h2 class="text-center">Result</h2>
  <table class="table table-bordered table-sm text-center">
    <thead>
      <tr>
        <th>Candidate Name</th>
        <th>Candidate Position</th>
        <th>Total Vote</th>
      </tr>
    </thead>
    <tbody>
      {% for i in obj %}
        <tr>
          <td>{{ i.name }}</td>
          <td>{{ i.position }}</td>
          <td>{{ i.total_vote }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}